name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Remove File
        uses: JesseTG/rm@v1.0.0
        with:
          path: en.subject.pdf
